apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-app
    app.kubernetes.io/managed-by: Helm
  name: php-app
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: php-app
    
# status:
#   loadBalancer: {}
