apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: livenessprobe
  name: livenessprobe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livenessprobe
  #strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: livenessprobe
    spec:
      containers:
      - image: busybox
        name: busybox
   #     resources: {}
#status: {}
        args:
          - /bin/sh
          - -c
          - sleep 20; touch hello; sleep 700
        livenessProbe:
          exec:
             command:
              - cat
              - hello 
          initialDelaySeconds: 15
          periodSeconds: 3
            
