apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: l124-hw20
  region: us-east-1
nodeGroups:
  - name: ng1
    desiredCapacity: 3
    instanceType: t2.micro
  - name: ng2
    desiredCapacity: 3
    instanceType: t2.micro
