apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  #namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: 097084951758.dkr.ecr.us-east-1.amazonaws.com/web:latest
          ports:
            - containerPort: 80