# apiVersion: v1
# kind: Service
# metadata:
#   name: php-app
# spec:
#   selector:
#     app: php
#   ports:
#   - name: http
#     port: 80
#     targetPort: 80

apiVersion: v1
kind: Service
metadata:
#  namespace: game-2048
  name: php-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: php-app